version: '3.7'

services:
  flask_gunicorn:
    volumes:
      - static:/static
    build:
      context: .
    ports:
      - "5000:5000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - flask_gunicorn

volumes:
  static:
